#ifndef GOOLNN_RSLIKE_PRIV_ENUM_H
#define GOOLNN_RSLIKE_PRIV_ENUM_H

#include "rslike/priv/util.h"

#define _priv_varient_0(n)
#define _priv_varient_1(n, v) _priv_combine(n, v),
#define _priv_varient_2(n, v, ...) _priv_combine(n, v), _priv_varient_1(n, __VA_ARGS__)
#define _priv_varient_3(n, v, ...) _priv_combine(n, v), _priv_varient_2(n, __VA_ARGS__)
#define _priv_varient_4(n, v, ...) _priv_combine(n, v), _priv_varient_3(n, __VA_ARGS__)
#define _priv_varient_5(n, v, ...) _priv_combine(n, v), _priv_varient_4(n, __VA_ARGS__)
#define _priv_varient_6(n, v, ...) _priv_combine(n, v), _priv_varient_5(n, __VA_ARGS__)
#define _priv_varient_7(n, v, ...) _priv_combine(n, v), _priv_varient_6(n, __VA_ARGS__)
#define _priv_varient_8(n, v, ...) _priv_combine(n, v), _priv_varient_7(n, __VA_ARGS__)
#define _priv_varient_9(n, v, ...) _priv_combine(n, v), _priv_varient_8(n, __VA_ARGS__)
#define _priv_varient_10(n, v, ...) _priv_combine(n, v), _priv_varient_9(n, __VA_ARGS__)
#define _priv_varient_11(n, v, ...) _priv_combine(n, v), _priv_varient_10(n, __VA_ARGS__)
#define _priv_varient_12(n, v, ...) _priv_combine(n, v), _priv_varient_11(n, __VA_ARGS__)
#define _priv_varient_13(n, v, ...) _priv_combine(n, v), _priv_varient_12(n, __VA_ARGS__)
#define _priv_varient_14(n, v, ...) _priv_combine(n, v), _priv_varient_13(n, __VA_ARGS__)
#define _priv_varient_15(n, v, ...) _priv_combine(n, v), _priv_varient_14(n, __VA_ARGS__)
#define _priv_varient_16(n, v, ...) _priv_combine(n, v), _priv_varient_15(n, __VA_ARGS__)
#define _priv_varient_17(n, v, ...) _priv_combine(n, v), _priv_varient_16(n, __VA_ARGS__)
#define _priv_varient_18(n, v, ...) _priv_combine(n, v), _priv_varient_17(n, __VA_ARGS__)
#define _priv_varient_19(n, v, ...) _priv_combine(n, v), _priv_varient_18(n, __VA_ARGS__)
#define _priv_varient_20(n, v, ...) _priv_combine(n, v), _priv_varient_19(n, __VA_ARGS__)
#define _priv_varient_21(n, v, ...) _priv_combine(n, v), _priv_varient_20(n, __VA_ARGS__)
#define _priv_varient_22(n, v, ...) _priv_combine(n, v), _priv_varient_21(n, __VA_ARGS__)
#define _priv_varient_23(n, v, ...) _priv_combine(n, v), _priv_varient_22(n, __VA_ARGS__)
#define _priv_varient_24(n, v, ...) _priv_combine(n, v), _priv_varient_23(n, __VA_ARGS__)
#define _priv_varient_25(n, v, ...) _priv_combine(n, v), _priv_varient_24(n, __VA_ARGS__)
#define _priv_varient_26(n, v, ...) _priv_combine(n, v), _priv_varient_25(n, __VA_ARGS__)
#define _priv_varient_27(n, v, ...) _priv_combine(n, v), _priv_varient_26(n, __VA_ARGS__)
#define _priv_varient_28(n, v, ...) _priv_combine(n, v), _priv_varient_27(n, __VA_ARGS__)
#define _priv_varient_29(n, v, ...) _priv_combine(n, v), _priv_varient_28(n, __VA_ARGS__)
#define _priv_varient_30(n, v, ...) _priv_combine(n, v), _priv_varient_29(n, __VA_ARGS__)
#define _priv_varient_31(n, v, ...) _priv_combine(n, v), _priv_varient_30(n, __VA_ARGS__)
#define _priv_varient_32(n, v, ...) _priv_combine(n, v), _priv_varient_31(n, __VA_ARGS__)
#define _priv_varient_33(n, v, ...) _priv_combine(n, v), _priv_varient_32(n, __VA_ARGS__)
#define _priv_varient_34(n, v, ...) _priv_combine(n, v), _priv_varient_33(n, __VA_ARGS__)
#define _priv_varient_35(n, v, ...) _priv_combine(n, v), _priv_varient_34(n, __VA_ARGS__)
#define _priv_varient_36(n, v, ...) _priv_combine(n, v), _priv_varient_35(n, __VA_ARGS__)
#define _priv_varient_37(n, v, ...) _priv_combine(n, v), _priv_varient_36(n, __VA_ARGS__)
#define _priv_varient_38(n, v, ...) _priv_combine(n, v), _priv_varient_37(n, __VA_ARGS__)
#define _priv_varient_39(n, v, ...) _priv_combine(n, v), _priv_varient_38(n, __VA_ARGS__)
#define _priv_varient_40(n, v, ...) _priv_combine(n, v), _priv_varient_39(n, __VA_ARGS__)
#define _priv_varient_41(n, v, ...) _priv_combine(n, v), _priv_varient_40(n, __VA_ARGS__)
#define _priv_varient_42(n, v, ...) _priv_combine(n, v), _priv_varient_41(n, __VA_ARGS__)
#define _priv_varient_43(n, v, ...) _priv_combine(n, v), _priv_varient_42(n, __VA_ARGS__)
#define _priv_varient_44(n, v, ...) _priv_combine(n, v), _priv_varient_43(n, __VA_ARGS__)
#define _priv_varient_45(n, v, ...) _priv_combine(n, v), _priv_varient_44(n, __VA_ARGS__)
#define _priv_varient_46(n, v, ...) _priv_combine(n, v), _priv_varient_45(n, __VA_ARGS__)
#define _priv_varient_47(n, v, ...) _priv_combine(n, v), _priv_varient_46(n, __VA_ARGS__)
#define _priv_varient_48(n, v, ...) _priv_combine(n, v), _priv_varient_47(n, __VA_ARGS__)
#define _priv_varient_49(n, v, ...) _priv_combine(n, v), _priv_varient_48(n, __VA_ARGS__)
#define _priv_varient_50(n, v, ...) _priv_combine(n, v), _priv_varient_49(n, __VA_ARGS__)
#define _priv_varient_51(n, v, ...) _priv_combine(n, v), _priv_varient_50(n, __VA_ARGS__)
#define _priv_varient_52(n, v, ...) _priv_combine(n, v), _priv_varient_51(n, __VA_ARGS__)
#define _priv_varient_53(n, v, ...) _priv_combine(n, v), _priv_varient_52(n, __VA_ARGS__)
#define _priv_varient_54(n, v, ...) _priv_combine(n, v), _priv_varient_53(n, __VA_ARGS__)
#define _priv_varient_55(n, v, ...) _priv_combine(n, v), _priv_varient_54(n, __VA_ARGS__)
#define _priv_varient_56(n, v, ...) _priv_combine(n, v), _priv_varient_55(n, __VA_ARGS__)
#define _priv_varient_57(n, v, ...) _priv_combine(n, v), _priv_varient_56(n, __VA_ARGS__)
#define _priv_varient_58(n, v, ...) _priv_combine(n, v), _priv_varient_57(n, __VA_ARGS__)
#define _priv_varient_59(n, v, ...) _priv_combine(n, v), _priv_varient_58(n, __VA_ARGS__)
#define _priv_varient_60(n, v, ...) _priv_combine(n, v), _priv_varient_59(n, __VA_ARGS__)
#define _priv_varient_61(n, v, ...) _priv_combine(n, v), _priv_varient_60(n, __VA_ARGS__)
#define _priv_varient_62(n, v, ...) _priv_combine(n, v), _priv_varient_61(n, __VA_ARGS__)
#define _priv_varient_63(n, v, ...) _priv_combine(n, v), _priv_varient_62(n, __VA_ARGS__)

#define _priv_varient(n, ...) _priv_overload(_priv_varient, _priv_argc(__VA_ARGS__))(n __VA_OPT__(,) __VA_ARGS__)

#endif
