#ifndef GOOLNN_RSLIKE_PRIV_ENUM_H
#define GOOLNN_RSLIKE_PRIV_ENUM_H

#include <xmacros/xmacros.h>

#define priv_variant_name_case(n, v, s) \
case xmacros_combine(n, v):             \
    return #s;

#define priv_parse_case_0(a) a
#define priv_parse_case_1(v) xmacros_argn(0, xmacros_unwrap v)

#define priv_parse_case(v) xmacros_overload(priv_parse_case, xmacros_is_paren(v))(v)

#define priv_variant_name_string(n, v, s) priv_variant_name_case(n, v, s)
#define priv_variant_name_case_apply(n, v) priv_variant_name_string(n, v, xmacros_concat(n, ::, v))

#define priv_variant_name_0(n)
#define priv_variant_name_1(n, v) priv_variant_name_case_apply(n, priv_parse_case(v))
#define priv_variant_name_2(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_1(n, __VA_ARGS__)
#define priv_variant_name_3(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_2(n, __VA_ARGS__)
#define priv_variant_name_4(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_3(n, __VA_ARGS__)
#define priv_variant_name_5(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_4(n, __VA_ARGS__)
#define priv_variant_name_6(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_5(n, __VA_ARGS__)
#define priv_variant_name_7(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_6(n, __VA_ARGS__)
#define priv_variant_name_8(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_7(n, __VA_ARGS__)
#define priv_variant_name_9(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_8(n, __VA_ARGS__)
#define priv_variant_name_10(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_9(n, __VA_ARGS__)
#define priv_variant_name_11(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_10(n, __VA_ARGS__)
#define priv_variant_name_12(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_11(n, __VA_ARGS__)
#define priv_variant_name_13(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_12(n, __VA_ARGS__)
#define priv_variant_name_14(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_13(n, __VA_ARGS__)
#define priv_variant_name_15(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_14(n, __VA_ARGS__)
#define priv_variant_name_16(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_15(n, __VA_ARGS__)
#define priv_variant_name_17(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_16(n, __VA_ARGS__)
#define priv_variant_name_18(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_17(n, __VA_ARGS__)
#define priv_variant_name_19(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_18(n, __VA_ARGS__)
#define priv_variant_name_20(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_19(n, __VA_ARGS__)
#define priv_variant_name_21(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_20(n, __VA_ARGS__)
#define priv_variant_name_22(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_21(n, __VA_ARGS__)
#define priv_variant_name_23(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_22(n, __VA_ARGS__)
#define priv_variant_name_24(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_23(n, __VA_ARGS__)
#define priv_variant_name_25(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_24(n, __VA_ARGS__)
#define priv_variant_name_26(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_25(n, __VA_ARGS__)
#define priv_variant_name_27(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_26(n, __VA_ARGS__)
#define priv_variant_name_28(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_27(n, __VA_ARGS__)
#define priv_variant_name_29(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_28(n, __VA_ARGS__)
#define priv_variant_name_30(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_29(n, __VA_ARGS__)
#define priv_variant_name_31(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_30(n, __VA_ARGS__)
#define priv_variant_name_32(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_31(n, __VA_ARGS__)
#define priv_variant_name_33(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_32(n, __VA_ARGS__)
#define priv_variant_name_34(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_33(n, __VA_ARGS__)
#define priv_variant_name_35(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_34(n, __VA_ARGS__)
#define priv_variant_name_36(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_35(n, __VA_ARGS__)
#define priv_variant_name_37(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_36(n, __VA_ARGS__)
#define priv_variant_name_38(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_37(n, __VA_ARGS__)
#define priv_variant_name_39(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_38(n, __VA_ARGS__)
#define priv_variant_name_40(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_39(n, __VA_ARGS__)
#define priv_variant_name_41(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_40(n, __VA_ARGS__)
#define priv_variant_name_42(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_41(n, __VA_ARGS__)
#define priv_variant_name_43(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_42(n, __VA_ARGS__)
#define priv_variant_name_44(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_43(n, __VA_ARGS__)
#define priv_variant_name_45(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_44(n, __VA_ARGS__)
#define priv_variant_name_46(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_45(n, __VA_ARGS__)
#define priv_variant_name_47(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_46(n, __VA_ARGS__)
#define priv_variant_name_48(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_47(n, __VA_ARGS__)
#define priv_variant_name_49(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_48(n, __VA_ARGS__)
#define priv_variant_name_50(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_49(n, __VA_ARGS__)
#define priv_variant_name_51(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_50(n, __VA_ARGS__)
#define priv_variant_name_52(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_51(n, __VA_ARGS__)
#define priv_variant_name_53(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_52(n, __VA_ARGS__)
#define priv_variant_name_54(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_53(n, __VA_ARGS__)
#define priv_variant_name_55(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_54(n, __VA_ARGS__)
#define priv_variant_name_56(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_55(n, __VA_ARGS__)
#define priv_variant_name_57(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_56(n, __VA_ARGS__)
#define priv_variant_name_58(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_57(n, __VA_ARGS__)
#define priv_variant_name_59(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_58(n, __VA_ARGS__)
#define priv_variant_name_60(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_59(n, __VA_ARGS__)
#define priv_variant_name_61(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_60(n, __VA_ARGS__)
#define priv_variant_name_62(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_61(n, __VA_ARGS__)
#define priv_variant_name_63(n, v, ...) priv_variant_name_case_apply(n, priv_parse_case(v)) priv_variant_name_62(n, __VA_ARGS__)

#define priv_assign(a, b) a = b

#define priv_parse_variant_0(a) a
#define priv_parse_variant_1(v) priv_assign v

#define priv_parse_variant(v) xmacros_overload(priv_parse_variant, xmacros_is_paren(v))(v)

#define priv_variant_0(n)
#define priv_variant_1(n, v) xmacros_combine(n, priv_parse_variant(v)),
#define priv_variant_2(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_1(n, __VA_ARGS__)
#define priv_variant_3(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_2(n, __VA_ARGS__)
#define priv_variant_4(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_3(n, __VA_ARGS__)
#define priv_variant_5(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_4(n, __VA_ARGS__)
#define priv_variant_6(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_5(n, __VA_ARGS__)
#define priv_variant_7(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_6(n, __VA_ARGS__)
#define priv_variant_8(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_7(n, __VA_ARGS__)
#define priv_variant_9(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_8(n, __VA_ARGS__)
#define priv_variant_10(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_9(n, __VA_ARGS__)
#define priv_variant_11(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_10(n, __VA_ARGS__)
#define priv_variant_12(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_11(n, __VA_ARGS__)
#define priv_variant_13(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_12(n, __VA_ARGS__)
#define priv_variant_14(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_13(n, __VA_ARGS__)
#define priv_variant_15(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_14(n, __VA_ARGS__)
#define priv_variant_16(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_15(n, __VA_ARGS__)
#define priv_variant_17(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_16(n, __VA_ARGS__)
#define priv_variant_18(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_17(n, __VA_ARGS__)
#define priv_variant_19(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_18(n, __VA_ARGS__)
#define priv_variant_20(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_19(n, __VA_ARGS__)
#define priv_variant_21(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_20(n, __VA_ARGS__)
#define priv_variant_22(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_21(n, __VA_ARGS__)
#define priv_variant_23(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_22(n, __VA_ARGS__)
#define priv_variant_24(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_23(n, __VA_ARGS__)
#define priv_variant_25(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_24(n, __VA_ARGS__)
#define priv_variant_26(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_25(n, __VA_ARGS__)
#define priv_variant_27(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_26(n, __VA_ARGS__)
#define priv_variant_28(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_27(n, __VA_ARGS__)
#define priv_variant_29(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_28(n, __VA_ARGS__)
#define priv_variant_30(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_29(n, __VA_ARGS__)
#define priv_variant_31(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_30(n, __VA_ARGS__)
#define priv_variant_32(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_31(n, __VA_ARGS__)
#define priv_variant_33(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_32(n, __VA_ARGS__)
#define priv_variant_34(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_33(n, __VA_ARGS__)
#define priv_variant_35(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_34(n, __VA_ARGS__)
#define priv_variant_36(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_35(n, __VA_ARGS__)
#define priv_variant_37(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_36(n, __VA_ARGS__)
#define priv_variant_38(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_37(n, __VA_ARGS__)
#define priv_variant_39(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_38(n, __VA_ARGS__)
#define priv_variant_40(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_39(n, __VA_ARGS__)
#define priv_variant_41(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_40(n, __VA_ARGS__)
#define priv_variant_42(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_41(n, __VA_ARGS__)
#define priv_variant_43(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_42(n, __VA_ARGS__)
#define priv_variant_44(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_43(n, __VA_ARGS__)
#define priv_variant_45(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_44(n, __VA_ARGS__)
#define priv_variant_46(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_45(n, __VA_ARGS__)
#define priv_variant_47(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_46(n, __VA_ARGS__)
#define priv_variant_48(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_47(n, __VA_ARGS__)
#define priv_variant_49(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_48(n, __VA_ARGS__)
#define priv_variant_50(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_49(n, __VA_ARGS__)
#define priv_variant_51(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_50(n, __VA_ARGS__)
#define priv_variant_52(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_51(n, __VA_ARGS__)
#define priv_variant_53(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_52(n, __VA_ARGS__)
#define priv_variant_54(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_53(n, __VA_ARGS__)
#define priv_variant_55(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_54(n, __VA_ARGS__)
#define priv_variant_56(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_55(n, __VA_ARGS__)
#define priv_variant_57(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_56(n, __VA_ARGS__)
#define priv_variant_58(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_57(n, __VA_ARGS__)
#define priv_variant_59(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_58(n, __VA_ARGS__)
#define priv_variant_60(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_59(n, __VA_ARGS__)
#define priv_variant_61(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_60(n, __VA_ARGS__)
#define priv_variant_62(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_61(n, __VA_ARGS__)
#define priv_variant_63(n, v, ...) xmacros_combine(n, priv_parse_variant(v)), priv_variant_62(n, __VA_ARGS__)

#define priv_variant_name(n, ...) xmacros_overload(priv_variant_name, xmacros_argc(__VA_ARGS__))(n __VA_OPT__(,) __VA_ARGS__)
#define priv_variant(n, ...) xmacros_overload(priv_variant, xmacros_argc(__VA_ARGS__))(n __VA_OPT__(,) __VA_ARGS__)

#endif
