#ifndef GOOLNN_RSLIKE_PRIV_H
#define GOOLNN_RSLIKE_PRIV_H

#include <xmacros/xmacros.h>

#define priv_param_0()
#define priv_param_1(arg) priv_exchange arg
#define priv_param_2(arg, ...) priv_exchange arg, priv_param_1(__VA_ARGS__)
#define priv_param_3(arg, ...) priv_exchange arg, priv_param_2(__VA_ARGS__)
#define priv_param_4(arg, ...) priv_exchange arg, priv_param_3(__VA_ARGS__)
#define priv_param_5(arg, ...) priv_exchange arg, priv_param_4(__VA_ARGS__)
#define priv_param_6(arg, ...) priv_exchange arg, priv_param_5(__VA_ARGS__)
#define priv_param_7(arg, ...) priv_exchange arg, priv_param_6(__VA_ARGS__)
#define priv_param_8(arg, ...) priv_exchange arg, priv_param_7(__VA_ARGS__)
#define priv_param_9(arg, ...) priv_exchange arg, priv_param_8(__VA_ARGS__)
#define priv_param_10(arg, ...) priv_exchange arg, priv_param_9(__VA_ARGS__)
#define priv_param_11(arg, ...) priv_exchange arg, priv_param_10(__VA_ARGS__)
#define priv_param_12(arg, ...) priv_exchange arg, priv_param_11(__VA_ARGS__)
#define priv_param_13(arg, ...) priv_exchange arg, priv_param_12(__VA_ARGS__)
#define priv_param_14(arg, ...) priv_exchange arg, priv_param_13(__VA_ARGS__)
#define priv_param_15(arg, ...) priv_exchange arg, priv_param_14(__VA_ARGS__)
#define priv_param_16(arg, ...) priv_exchange arg, priv_param_15(__VA_ARGS__)
#define priv_param_17(arg, ...) priv_exchange arg, priv_param_16(__VA_ARGS__)
#define priv_param_18(arg, ...) priv_exchange arg, priv_param_17(__VA_ARGS__)
#define priv_param_19(arg, ...) priv_exchange arg, priv_param_18(__VA_ARGS__)
#define priv_param_20(arg, ...) priv_exchange arg, priv_param_19(__VA_ARGS__)
#define priv_param_21(arg, ...) priv_exchange arg, priv_param_20(__VA_ARGS__)
#define priv_param_22(arg, ...) priv_exchange arg, priv_param_21(__VA_ARGS__)
#define priv_param_23(arg, ...) priv_exchange arg, priv_param_22(__VA_ARGS__)
#define priv_param_24(arg, ...) priv_exchange arg, priv_param_23(__VA_ARGS__)
#define priv_param_25(arg, ...) priv_exchange arg, priv_param_24(__VA_ARGS__)
#define priv_param_26(arg, ...) priv_exchange arg, priv_param_25(__VA_ARGS__)
#define priv_param_27(arg, ...) priv_exchange arg, priv_param_26(__VA_ARGS__)
#define priv_param_28(arg, ...) priv_exchange arg, priv_param_27(__VA_ARGS__)
#define priv_param_29(arg, ...) priv_exchange arg, priv_param_28(__VA_ARGS__)
#define priv_param_30(arg, ...) priv_exchange arg, priv_param_29(__VA_ARGS__)
#define priv_param_31(arg, ...) priv_exchange arg, priv_param_30(__VA_ARGS__)
#define priv_param_32(arg, ...) priv_exchange arg, priv_param_31(__VA_ARGS__)
#define priv_param_33(arg, ...) priv_exchange arg, priv_param_32(__VA_ARGS__)
#define priv_param_34(arg, ...) priv_exchange arg, priv_param_33(__VA_ARGS__)
#define priv_param_35(arg, ...) priv_exchange arg, priv_param_34(__VA_ARGS__)
#define priv_param_36(arg, ...) priv_exchange arg, priv_param_35(__VA_ARGS__)
#define priv_param_37(arg, ...) priv_exchange arg, priv_param_36(__VA_ARGS__)
#define priv_param_38(arg, ...) priv_exchange arg, priv_param_37(__VA_ARGS__)
#define priv_param_39(arg, ...) priv_exchange arg, priv_param_38(__VA_ARGS__)
#define priv_param_40(arg, ...) priv_exchange arg, priv_param_39(__VA_ARGS__)
#define priv_param_41(arg, ...) priv_exchange arg, priv_param_40(__VA_ARGS__)
#define priv_param_42(arg, ...) priv_exchange arg, priv_param_41(__VA_ARGS__)
#define priv_param_43(arg, ...) priv_exchange arg, priv_param_42(__VA_ARGS__)
#define priv_param_44(arg, ...) priv_exchange arg, priv_param_43(__VA_ARGS__)
#define priv_param_45(arg, ...) priv_exchange arg, priv_param_44(__VA_ARGS__)
#define priv_param_46(arg, ...) priv_exchange arg, priv_param_45(__VA_ARGS__)
#define priv_param_47(arg, ...) priv_exchange arg, priv_param_46(__VA_ARGS__)
#define priv_param_48(arg, ...) priv_exchange arg, priv_param_47(__VA_ARGS__)
#define priv_param_49(arg, ...) priv_exchange arg, priv_param_48(__VA_ARGS__)
#define priv_param_50(arg, ...) priv_exchange arg, priv_param_49(__VA_ARGS__)
#define priv_param_51(arg, ...) priv_exchange arg, priv_param_50(__VA_ARGS__)
#define priv_param_52(arg, ...) priv_exchange arg, priv_param_51(__VA_ARGS__)
#define priv_param_53(arg, ...) priv_exchange arg, priv_param_52(__VA_ARGS__)
#define priv_param_54(arg, ...) priv_exchange arg, priv_param_53(__VA_ARGS__)
#define priv_param_55(arg, ...) priv_exchange arg, priv_param_54(__VA_ARGS__)
#define priv_param_56(arg, ...) priv_exchange arg, priv_param_55(__VA_ARGS__)
#define priv_param_57(arg, ...) priv_exchange arg, priv_param_56(__VA_ARGS__)
#define priv_param_58(arg, ...) priv_exchange arg, priv_param_57(__VA_ARGS__)
#define priv_param_59(arg, ...) priv_exchange arg, priv_param_58(__VA_ARGS__)
#define priv_param_60(arg, ...) priv_exchange arg, priv_param_59(__VA_ARGS__)
#define priv_param_61(arg, ...) priv_exchange arg, priv_param_60(__VA_ARGS__)
#define priv_param_62(arg, ...) priv_exchange arg, priv_param_61(__VA_ARGS__)
#define priv_param_63(arg, ...) priv_exchange arg, priv_param_62(__VA_ARGS__)

#define priv_return(...) xmacros_argn(0, __VA_OPT__(__VA_ARGS__, ) void)
#define priv_param(...) xmacros_overload(priv_param, xmacros_argc(__VA_ARGS__))(__VA_ARGS__)

#define priv_func(n, p, ...) priv_return(__VA_ARGS__) n (priv_param p)

#endif
