#ifndef GOOLNN_RSLIKE_PRIV_STRUCT_H
#define GOOLNN_RSLIKE_PRIV_STRUCT_H

#include "rslike/priv/util.h"

#define _priv_member_0()
#define _priv_member_1(arg) _priv_exchange arg;
#define _priv_member_2(arg, ...) _priv_exchange arg; _priv_member_1(__VA_ARGS__)
#define _priv_member_3(arg, ...) _priv_exchange arg; _priv_member_2(__VA_ARGS__)
#define _priv_member_4(arg, ...) _priv_exchange arg; _priv_member_3(__VA_ARGS__)
#define _priv_member_5(arg, ...) _priv_exchange arg; _priv_member_4(__VA_ARGS__)
#define _priv_member_6(arg, ...) _priv_exchange arg; _priv_member_5(__VA_ARGS__)
#define _priv_member_7(arg, ...) _priv_exchange arg; _priv_member_6(__VA_ARGS__)
#define _priv_member_8(arg, ...) _priv_exchange arg; _priv_member_7(__VA_ARGS__)
#define _priv_member_9(arg, ...) _priv_exchange arg; _priv_member_8(__VA_ARGS__)
#define _priv_member_10(arg, ...) _priv_exchange arg; _priv_member_9(__VA_ARGS__)
#define _priv_member_11(arg, ...) _priv_exchange arg; _priv_member_10(__VA_ARGS__)
#define _priv_member_12(arg, ...) _priv_exchange arg; _priv_member_11(__VA_ARGS__)
#define _priv_member_13(arg, ...) _priv_exchange arg; _priv_member_12(__VA_ARGS__)
#define _priv_member_14(arg, ...) _priv_exchange arg; _priv_member_13(__VA_ARGS__)
#define _priv_member_15(arg, ...) _priv_exchange arg; _priv_member_14(__VA_ARGS__)
#define _priv_member_16(arg, ...) _priv_exchange arg; _priv_member_15(__VA_ARGS__)
#define _priv_member_17(arg, ...) _priv_exchange arg; _priv_member_16(__VA_ARGS__)
#define _priv_member_18(arg, ...) _priv_exchange arg; _priv_member_17(__VA_ARGS__)
#define _priv_member_19(arg, ...) _priv_exchange arg; _priv_member_18(__VA_ARGS__)
#define _priv_member_20(arg, ...) _priv_exchange arg; _priv_member_19(__VA_ARGS__)
#define _priv_member_21(arg, ...) _priv_exchange arg; _priv_member_20(__VA_ARGS__)
#define _priv_member_22(arg, ...) _priv_exchange arg; _priv_member_21(__VA_ARGS__)
#define _priv_member_23(arg, ...) _priv_exchange arg; _priv_member_22(__VA_ARGS__)
#define _priv_member_24(arg, ...) _priv_exchange arg; _priv_member_23(__VA_ARGS__)
#define _priv_member_25(arg, ...) _priv_exchange arg; _priv_member_24(__VA_ARGS__)
#define _priv_member_26(arg, ...) _priv_exchange arg; _priv_member_25(__VA_ARGS__)
#define _priv_member_27(arg, ...) _priv_exchange arg; _priv_member_26(__VA_ARGS__)
#define _priv_member_28(arg, ...) _priv_exchange arg; _priv_member_27(__VA_ARGS__)
#define _priv_member_29(arg, ...) _priv_exchange arg; _priv_member_28(__VA_ARGS__)
#define _priv_member_30(arg, ...) _priv_exchange arg; _priv_member_29(__VA_ARGS__)
#define _priv_member_31(arg, ...) _priv_exchange arg; _priv_member_30(__VA_ARGS__)
#define _priv_member_32(arg, ...) _priv_exchange arg; _priv_member_31(__VA_ARGS__)
#define _priv_member_33(arg, ...) _priv_exchange arg; _priv_member_32(__VA_ARGS__)
#define _priv_member_34(arg, ...) _priv_exchange arg; _priv_member_33(__VA_ARGS__)
#define _priv_member_35(arg, ...) _priv_exchange arg; _priv_member_34(__VA_ARGS__)
#define _priv_member_36(arg, ...) _priv_exchange arg; _priv_member_35(__VA_ARGS__)
#define _priv_member_37(arg, ...) _priv_exchange arg; _priv_member_36(__VA_ARGS__)
#define _priv_member_38(arg, ...) _priv_exchange arg; _priv_member_37(__VA_ARGS__)
#define _priv_member_39(arg, ...) _priv_exchange arg; _priv_member_38(__VA_ARGS__)
#define _priv_member_40(arg, ...) _priv_exchange arg; _priv_member_39(__VA_ARGS__)
#define _priv_member_41(arg, ...) _priv_exchange arg; _priv_member_40(__VA_ARGS__)
#define _priv_member_42(arg, ...) _priv_exchange arg; _priv_member_41(__VA_ARGS__)
#define _priv_member_43(arg, ...) _priv_exchange arg; _priv_member_42(__VA_ARGS__)
#define _priv_member_44(arg, ...) _priv_exchange arg; _priv_member_43(__VA_ARGS__)
#define _priv_member_45(arg, ...) _priv_exchange arg; _priv_member_44(__VA_ARGS__)
#define _priv_member_46(arg, ...) _priv_exchange arg; _priv_member_45(__VA_ARGS__)
#define _priv_member_47(arg, ...) _priv_exchange arg; _priv_member_46(__VA_ARGS__)
#define _priv_member_48(arg, ...) _priv_exchange arg; _priv_member_47(__VA_ARGS__)
#define _priv_member_49(arg, ...) _priv_exchange arg; _priv_member_48(__VA_ARGS__)
#define _priv_member_50(arg, ...) _priv_exchange arg; _priv_member_49(__VA_ARGS__)
#define _priv_member_51(arg, ...) _priv_exchange arg; _priv_member_50(__VA_ARGS__)
#define _priv_member_52(arg, ...) _priv_exchange arg; _priv_member_51(__VA_ARGS__)
#define _priv_member_53(arg, ...) _priv_exchange arg; _priv_member_52(__VA_ARGS__)
#define _priv_member_54(arg, ...) _priv_exchange arg; _priv_member_53(__VA_ARGS__)
#define _priv_member_55(arg, ...) _priv_exchange arg; _priv_member_54(__VA_ARGS__)
#define _priv_member_56(arg, ...) _priv_exchange arg; _priv_member_55(__VA_ARGS__)
#define _priv_member_57(arg, ...) _priv_exchange arg; _priv_member_56(__VA_ARGS__)
#define _priv_member_58(arg, ...) _priv_exchange arg; _priv_member_57(__VA_ARGS__)
#define _priv_member_59(arg, ...) _priv_exchange arg; _priv_member_58(__VA_ARGS__)
#define _priv_member_60(arg, ...) _priv_exchange arg; _priv_member_59(__VA_ARGS__)
#define _priv_member_61(arg, ...) _priv_exchange arg; _priv_member_60(__VA_ARGS__)
#define _priv_member_62(arg, ...) _priv_exchange arg; _priv_member_61(__VA_ARGS__)
#define _priv_member_63(arg, ...) _priv_exchange arg; _priv_member_62(__VA_ARGS__)

#define _priv_member(...) _priv_overload(_priv_member, _priv_argc(__VA_ARGS__))(__VA_ARGS__)

#endif
