#ifndef GOOLNN_RSLIKE_PRIV_STRUCT_H
#define GOOLNN_RSLIKE_PRIV_STRUCT_H

#include "rslike/priv/util.h"

#define _priv_define_0()
#define _priv_define_1(arg) _priv_exchange arg;
#define _priv_define_2(arg, ...) _priv_exchange arg; _priv_define_1(__VA_ARGS__)
#define _priv_define_3(arg, ...) _priv_exchange arg; _priv_define_2(__VA_ARGS__)
#define _priv_define_4(arg, ...) _priv_exchange arg; _priv_define_3(__VA_ARGS__)
#define _priv_define_5(arg, ...) _priv_exchange arg; _priv_define_4(__VA_ARGS__)
#define _priv_define_6(arg, ...) _priv_exchange arg; _priv_define_5(__VA_ARGS__)
#define _priv_define_7(arg, ...) _priv_exchange arg; _priv_define_6(__VA_ARGS__)
#define _priv_define_8(arg, ...) _priv_exchange arg; _priv_define_7(__VA_ARGS__)
#define _priv_define_9(arg, ...) _priv_exchange arg; _priv_define_8(__VA_ARGS__)
#define _priv_define_10(arg, ...) _priv_exchange arg; _priv_define_9(__VA_ARGS__)
#define _priv_define_11(arg, ...) _priv_exchange arg; _priv_define_10(__VA_ARGS__)
#define _priv_define_12(arg, ...) _priv_exchange arg; _priv_define_11(__VA_ARGS__)
#define _priv_define_13(arg, ...) _priv_exchange arg; _priv_define_12(__VA_ARGS__)
#define _priv_define_14(arg, ...) _priv_exchange arg; _priv_define_13(__VA_ARGS__)
#define _priv_define_15(arg, ...) _priv_exchange arg; _priv_define_14(__VA_ARGS__)
#define _priv_define_16(arg, ...) _priv_exchange arg; _priv_define_15(__VA_ARGS__)
#define _priv_define_17(arg, ...) _priv_exchange arg; _priv_define_16(__VA_ARGS__)
#define _priv_define_18(arg, ...) _priv_exchange arg; _priv_define_17(__VA_ARGS__)
#define _priv_define_19(arg, ...) _priv_exchange arg; _priv_define_18(__VA_ARGS__)
#define _priv_define_20(arg, ...) _priv_exchange arg; _priv_define_19(__VA_ARGS__)
#define _priv_define_21(arg, ...) _priv_exchange arg; _priv_define_20(__VA_ARGS__)
#define _priv_define_22(arg, ...) _priv_exchange arg; _priv_define_21(__VA_ARGS__)
#define _priv_define_23(arg, ...) _priv_exchange arg; _priv_define_22(__VA_ARGS__)
#define _priv_define_24(arg, ...) _priv_exchange arg; _priv_define_23(__VA_ARGS__)
#define _priv_define_25(arg, ...) _priv_exchange arg; _priv_define_24(__VA_ARGS__)
#define _priv_define_26(arg, ...) _priv_exchange arg; _priv_define_25(__VA_ARGS__)
#define _priv_define_27(arg, ...) _priv_exchange arg; _priv_define_26(__VA_ARGS__)
#define _priv_define_28(arg, ...) _priv_exchange arg; _priv_define_27(__VA_ARGS__)
#define _priv_define_29(arg, ...) _priv_exchange arg; _priv_define_28(__VA_ARGS__)
#define _priv_define_30(arg, ...) _priv_exchange arg; _priv_define_29(__VA_ARGS__)
#define _priv_define_31(arg, ...) _priv_exchange arg; _priv_define_30(__VA_ARGS__)
#define _priv_define_32(arg, ...) _priv_exchange arg; _priv_define_31(__VA_ARGS__)
#define _priv_define_33(arg, ...) _priv_exchange arg; _priv_define_32(__VA_ARGS__)
#define _priv_define_34(arg, ...) _priv_exchange arg; _priv_define_33(__VA_ARGS__)
#define _priv_define_35(arg, ...) _priv_exchange arg; _priv_define_34(__VA_ARGS__)
#define _priv_define_36(arg, ...) _priv_exchange arg; _priv_define_35(__VA_ARGS__)
#define _priv_define_37(arg, ...) _priv_exchange arg; _priv_define_36(__VA_ARGS__)
#define _priv_define_38(arg, ...) _priv_exchange arg; _priv_define_37(__VA_ARGS__)
#define _priv_define_39(arg, ...) _priv_exchange arg; _priv_define_38(__VA_ARGS__)
#define _priv_define_40(arg, ...) _priv_exchange arg; _priv_define_39(__VA_ARGS__)
#define _priv_define_41(arg, ...) _priv_exchange arg; _priv_define_40(__VA_ARGS__)
#define _priv_define_42(arg, ...) _priv_exchange arg; _priv_define_41(__VA_ARGS__)
#define _priv_define_43(arg, ...) _priv_exchange arg; _priv_define_42(__VA_ARGS__)
#define _priv_define_44(arg, ...) _priv_exchange arg; _priv_define_43(__VA_ARGS__)
#define _priv_define_45(arg, ...) _priv_exchange arg; _priv_define_44(__VA_ARGS__)
#define _priv_define_46(arg, ...) _priv_exchange arg; _priv_define_45(__VA_ARGS__)
#define _priv_define_47(arg, ...) _priv_exchange arg; _priv_define_46(__VA_ARGS__)
#define _priv_define_48(arg, ...) _priv_exchange arg; _priv_define_47(__VA_ARGS__)
#define _priv_define_49(arg, ...) _priv_exchange arg; _priv_define_48(__VA_ARGS__)
#define _priv_define_50(arg, ...) _priv_exchange arg; _priv_define_49(__VA_ARGS__)
#define _priv_define_51(arg, ...) _priv_exchange arg; _priv_define_50(__VA_ARGS__)
#define _priv_define_52(arg, ...) _priv_exchange arg; _priv_define_51(__VA_ARGS__)
#define _priv_define_53(arg, ...) _priv_exchange arg; _priv_define_52(__VA_ARGS__)
#define _priv_define_54(arg, ...) _priv_exchange arg; _priv_define_53(__VA_ARGS__)
#define _priv_define_55(arg, ...) _priv_exchange arg; _priv_define_54(__VA_ARGS__)
#define _priv_define_56(arg, ...) _priv_exchange arg; _priv_define_55(__VA_ARGS__)
#define _priv_define_57(arg, ...) _priv_exchange arg; _priv_define_56(__VA_ARGS__)
#define _priv_define_58(arg, ...) _priv_exchange arg; _priv_define_57(__VA_ARGS__)
#define _priv_define_59(arg, ...) _priv_exchange arg; _priv_define_58(__VA_ARGS__)
#define _priv_define_60(arg, ...) _priv_exchange arg; _priv_define_59(__VA_ARGS__)
#define _priv_define_61(arg, ...) _priv_exchange arg; _priv_define_60(__VA_ARGS__)
#define _priv_define_62(arg, ...) _priv_exchange arg; _priv_define_61(__VA_ARGS__)
#define _priv_define_63(arg, ...) _priv_exchange arg; _priv_define_62(__VA_ARGS__)

#define _priv_define(...) _priv_overload(_priv_define, _priv_argc(__VA_ARGS__))(__VA_ARGS__)

#endif
